spring:
  application:
    name: zuul-service
  # Spring Cloud Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
# Eureka Discovery Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    order-service:
      path: /order-service/**
      url: http://localhost:8081